homepage:
    pattern:  /semdrops/
    defaults: { _controller: SemdropsSemdropsMobileBundle:Semdrops:index }

getCategories:
    pattern: /semdrops/get_categories/
    defaults: { _controller: SemdropsSemdropsMobileBundle:Semdrops:getCategories }

showCategories:
    pattern: /semdrops/show_categories/
    defaults: { _controller: SemdropsSemdropsMobileBundle:Semdrops:showCategories }

addCategory:
    pattern: /semdrops/add_category
    defaults: { _controller: SemdropsSemdropsMobileBundle:Semdrops:addCategory }

doneCategory:
    pattern: /donecategory
    defaults: { _controller: SemdropsSemdropsMobileBundle:Semdrops:doneCategory}

addPropertyTag:
    pattern: /semdrops/add_propertyTag
    defaults: { _controller: SemdropsSemdropsMobileBundle:Semdrops:addPropertyTag }

donePropertyTag:
    pattern: /semdrops/doneproperty
    defaults: { _controller: SemdropsSemdropsMobileBundle:Semdrops:donePropertyTag }

getProperties:
    pattern: /semdrops/get_properties/
    defaults: { _controller: SemdropsSemdropsMobileBundle:Semdrops:getProperties }    
    
showProperties:
    pattern: /semdrops/show_properties/
    defaults: { _controller: SemdropsSemdropsMobileBundle:Semdrops:showProperties }

addAttributeTag:
    pattern: /semdrops/add_attributeTag
    defaults: { _controller: SemdropsSemdropsMobileBundle:Semdrops:addAttributeTag }

doneAttributeTag:
    pattern: /semdrops/doneattribute
    defaults: { _controller: SemdropsSemdropsMobileBundle:Semdrops:doneAttributeTag }
    
getAttributes:
    pattern: /semdrops/get_attributes/
    defaults: { _controller: SemdropsSemdropsMobileBundle:Semdrops:getAttributes }    
    
showAttributes:
    pattern: /semdrops/show_attributes/
    defaults: { _controller: SemdropsSemdropsMobileBundle:Semdrops:showAttributes }
    

